package com.MainApp;

import javax.swing.*;
import java.awt.*;

public class OwnerHome extends JFrame {
    int ownerID;
    private JPanel OwnerHomeForm;

    public OwnerHome(int ID) {
      //  this();
        ownerID = ID;
    }

    /*public OwnerHome() {
        JFrame frame = new JFrame("Owner Home: Real Estate Broker System");
        frame.setContentPane(new OwnerHome().OwnerHomeForm);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }*/

    Container getForm() {
        return OwnerHomeForm;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        OwnerHomeForm = new JPanel();
        OwnerHomeForm.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return OwnerHomeForm;
    }
}
